---
- hosts: localhost
  vars_files:
    - variables.yml

  roles:
    - role: zsh
      tags:
      - init
    - role: packages
      become: yes
      become_method: sudo
    - role: ghq
    - role: aws-cli
    - role: docker-compose
    - role: ripgrep-all
    - role: google-chrome
