---
# tasks file for ripgrep-all

- name: Install packages
  ansible.builtin.package:
    name:
    - ripgrep
    - pandoc
    - poppler-utils
    - ffmpeg
    state: present
  become: yes
  become_method: sudo

# Check if we need to install rga first
- name: Check if rga is installed
  shell: command -v rga
  register: is_rga_installed
  ignore_errors: yes

- name: Get binary
  ansible.builtin.unarchive:
    src: https://github.com/phiresky/ripgrep-all/releases/download/v0.9.6/ripgrep_all-v0.9.6-x86_64-unknown-linux-musl.tar.gz
    dest: /tmp/
    remote_src: yes
    creates: /usr/local/bin/rga
  become: yes
  become_method: sudo
  when: is_rga_installed.rc != 0

- name: Copy rga binary
  ansible.builtin.copy:
    src: /tmp/ripgrep_all-v0.9.6-x86_64-unknown-linux-musl/rga
    dest: /usr/local/bin/rga
    mode: '0755'
    force: no
  become: yes
  become_method: sudo
  when: is_rga_installed.rc != 0

- name: Copy rga-preproc binary
  ansible.builtin.copy:
    src: /tmp/ripgrep_all-v0.9.6-x86_64-unknown-linux-musl/rga-preproc
    dest: /usr/local/bin/rga-preproc
    mode: '0755'
    force: no
  become: yes
  become_method: sudo
  when: is_rga_installed.rc != 0

# At this point rga is actually installed, but is_rga_installed.rc is still > 0, so we use it as a check still
- name: Remove the rga extracted directory in tmp/
  file: path=/tmp/ripgrep_all-v0.9.6-x86_64-unknown-linux-musl/ state=absent
  when: is_rga_installed.rc != 0
