---
# tasks file for packages
- name: Add repository for shutter
  ansible.builtin.apt_repository:
    repo: ppa:shutter/ppa
    state: present

- name: Add repository for pulseeffects
  ansible.builtin.apt_repository:
    repo: ppa:mikhailnov/pulseeffects
    state: present

- name: Install packages via the package manager
  ansible.builtin.package:
    name:
    - docker-ce
    - git
    - tilix
    - fzf
    - shutter
    - tig
    - speedcrunch
    - xtightvncviewer
    - pulseeffects
    state: present

- name: Install snap packages
  snap:
    name:
    - code
    - spotify
    classic: yes
    state: present
