---
# tasks file for packages
- name: Install packages via the package manager
  ansible.builtin.package:
    name:
    - docker-ce
    - git
    - tilix
    - fzf
    state: present

- name: Install snap packages
  snap:
    name:
    - code
    - spotify
    classic: yes
    state: present
