---
# tasks file for packages
- name: Install docker
  ansible.builtin.package:
    name: docker-ce
    state: present

- name: Install git
  ansible.builtin.package:
    name: git
    state: present

- name: Install tilix
  ansible.builtin.package:
    name: tilix
    state: present

- name: Install fzf
  ansible.builtin.package:
    name: fzf
    state: present

- name: Install snap for vscode
  snap:
    name: code
    classic: yes
    state: present

- name: Install snap for spotify
  snap:
    name: spotify
    classic: yes
    state: present
