---
# tasks file for packages
- name: Install basic packages
  ansible.builtin.package:
    name:
    - ca-certificates
    - curl
    - gnupg
    - lsb-release

- name: Add Docker GPG apt Key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker Repository
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu bionic stable
    state: present

- name: Add repository for shutter
  ansible.builtin.apt_repository:
    repo: ppa:shutter/ppa
    state: present

- name: Add repository for pulseeffects
  ansible.builtin.apt_repository:
    repo: ppa:mikhailnov/pulseeffects
    state: present

- name: Install applications via the package manager
  ansible.builtin.package:
    name:
    - docker-ce
    - tilix
    - fzf
    - shutter
    - speedcrunch
    - xtightvncviewer
    - pulseeffects
    - vim
    - htop
    - meld
    - ncdu
    - iotop
    - build-essential
    - git
    - tig
    - neofetch
    - vlc
    - tree
    - simple-scan
    - gitk
    - unifont # Fixes a bug with gitk and emojis in commits, see https://unix.stackexchange.com/questions/629281/gitk-crashes-when-viewing-commit-containing-emoji-x-error-of-failed-request-ba
    - tldr
    - ripgrep
    - pandoc # Dependency for ripgrep
    - poppler-utils # Dependency for ripgrep
    - ffmpeg # Dependency for ripgrep
    - httpie
    - fd-find
    - neovim
    state: present

- name: Workaround for installing bat
  command: apt install -y -o Dpkg::Options::="--force-overwrite" bat
  become: yes
  become_method: sudo

- name: Create a symbolic link for bat
  ansible.builtin.file:
    src: /usr/bin/batcat
    dest: /home/{{ user_name }}/.local/bin/bat
    owner: "{{ user_name }}"
    group: "{{ user_group }}"
    state: link

- name: Install duf as a .deb package from the internet
  apt:
    deb: https://github.com/muesli/duf/releases/download/v0.7.0/duf_0.7.0_linux_amd64.deb

- name: Install snap packages
  snap:
    name:
    - code
    - spotify
    classic: yes
    state: present

- name: Add user to docker group
  ansible.builtin.user:
    name: "{{ lookup('env','USER') }}"
    append: yes
    groups: docker
  become: yes
  become_method: sudo
