---
# tasks file for node

### NVM INSTALLATION ###

# Check if we need to install nvm first
- name: Check if nvm is installed
  shell: zsh -ic 'command -v nvm'
  register: is_nvm_installed
  ignore_errors: yes

- name: Download nvm installer
  get_url:
    url: https://raw.githubusercontent.com/nvm-sh/nvm/v{{ versions_nvm }}/install.sh
    dest: /tmp/nvm-installer.sh
    mode: 0755
  when: is_nvm_installed.rc != 0

- name: Execute the nvm-installer.sh
  shell: /tmp/nvm-installer.sh
  when: is_nvm_installed.rc != 0

- name: Remove the nvm-installer.sh
  file: path=/tmp/nvm-installer.sh state=absent
  when: is_nvm_installed.rc != 0

### NODE INSTALLATION ###

- name: Check if node is installed
  shell: zsh -ic 'nvm current'
  register: is_node_installed
  ignore_errors: yes

- name: Install node lts
  shell: zsh -ic 'nvm install --lts'
  when: is_node_installed.stdout == 'none'

- name: Use node lts
  shell: zsh -ic 'nvm use --lts'
  when: is_node_installed.stdout == 'none'
