---
# tasks file for zsh
- name: Git checkout
  ansible.builtin.git:
    repo: 'https://github.com/ohmyzsh/ohmyzsh.git'
    dest: ~/.oh-my-zsh
    version: master

- copy:
    src: .zshrc
    dest: ~/.zshrc

- copy:
    src: custom/
    dest: ~/.oh-my-zsh/custom

- name: Powerlevel checkout
  ansible.builtin.git:
    repo: 'https://github.com/romkatv/powerlevel10k.git'
    dest: ~/.oh-my-zsh/custom/themes/powerlevel10k
    version: master

- name: Setup default shell
  ansible.builtin.replace:
    path: /etc/sssd/sssd.conf
    regexp: '^default_shell = /bin/bash$'
    replace: 'default_shell = /usr/bin/zsh'
  become: yes
  become_method: sudo
  tags:
    - only-company

- name: Setup default shell
  ansible.builtin.user:
    name: "{{ lookup('env','USER') }}"
    shell: /usr/bin/zsh
  become: yes
  become_method: sudo
  tags:
    - only-private
