---
# tasks file for zsh
- name: Install the zsh package, and hard dependencies
  ansible.builtin.package:
    name:
    - zsh
    - git
    state: present
  become: yes
  become_method: sudo

- name: Git checkout
  ansible.builtin.git:
    repo: 'https://github.com/ohmyzsh/ohmyzsh.git'
    dest: ~/.oh-my-zsh
    version: master

- name:
  ansible.builtin.template:
    src: .zshrc
    dest: ~/.zshrc

- copy:
    src: custom/
    dest: ~/.oh-my-zsh/custom

- copy:
    src: .p10k.zsh
    dest: ~/.p10k.zsh

- name: Powerlevel checkout
  ansible.builtin.git:
    repo: 'https://github.com/romkatv/powerlevel10k.git'
    dest: ~/.oh-my-zsh/custom/themes/powerlevel10k
    version: master

- name: zsh syntax highlighting checkout
  ansible.builtin.git:
    repo: 'https://github.com/zsh-users/zsh-syntax-highlighting.git'
    dest: ~/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting
    version: master

- name: zsh autocompletion checkout
  ansible.builtin.git:
    repo: 'https://github.com/zsh-users/zsh-completions'
    dest: ~/.oh-my-zsh/custom/plugins/zsh-completions
    version: master

- name: Setup default shell in sssd.conf
  ansible.builtin.replace:
    path: /etc/sssd/sssd.conf
    regexp: '^default_shell = /bin/bash$'
    replace: 'default_shell = /usr/bin/zsh'
  become: yes
  become_method: sudo
  when: sssd == true

- name: Setup default shell via ansible.builtin.user
  ansible.builtin.user:
    name: "{{ lookup('env','USER') }}"
    shell: /usr/bin/zsh
  become: yes
  become_method: sudo
  when: sssd == false
