---
# tasks file for ghq
- name: Install golang
  ansible.builtin.unarchive:
    src: https://golang.org/dl/go1.17.2.linux-amd64.tar.gz
    dest: /usr/local
    remote_src: yes
    creates: /usr/local/go
  become: yes
  become_method: sudo

- name:
  ansible.builtin.template:
    src: .gitconfig
    dest: ~/.gitconfig

- name: Install ghq
  command: go install github.com/x-motemen/ghq@latest
  args:
    creates: /home/{{ user_name }}/go/bin/ghq
