---
- hosts: localhost
  vars_files:
    - ../variables.yml

  roles:
    - role: packages
      become: yes
      become_method: sudo
    - role: ghq
    - role: aws-cli
    - role: aws-sam
    - role: docker-compose
    - role: ripgrep-all
    - role: google-chrome
    - role: node
    - role: exa
    - role: terraform
    - role: keychron-f-keys
